### ISSUE TITLE
Missing dependencies in README

### ISSUE THREAD

**Issue by Paebbels** [deyuan/random-graph-generator#1]
The following dependencies are not listed in the README:
* `numpy` for random numbers
* `matplotlib` for visualization  
  The remark `Visualize graph with pyplot` doesn't seem correct, as matplotlib is requested
* `scipy` (when graphs grow ...)

------
This could be solved by:
1. Providing a setup.py for local installation including an entrypoint.
2. Packaging this code as a PyPI packaging.

**Comment by deyuan** [comment]
Thanks for your suggestions, Patrick. I just updated the dependencies part in README. numpy and scipy are not being used for now. I'll think about setup.py and PyPI packaging.
